#!/usr/bin/env bash
# Creating a script that uses if, elif, and else statements to print special messages on 4th and 8th iterations
x=1
while [ $x -le 10 ]
do
    if [ $x -eq 4 ]
    then
        echo "bad luck"
    elif [ $x -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((x++))
done
